services:
  - type: web
    name: SegundoParcial
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn luxor_site.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: luxor_site.settings
      - key: DATABASE_URL
        value: postgresql://segundoparcial_uhrr_user:7xqI2Gm0eog1sogumljqWTd8aqgNs7DS@dpg-d4jpne2li9vc73da5kd0-a.oregon-postgres.render.com/segundoparcial_uhrr
